### ISSUE TITLE
Error #001

### ISSUE THREAD

**Issue by winnipeg21** [zJerino/Mooz-Template#2]
I open the template section and hit install and I get an `Error #001`

**Comment by zJerino** [comment]
Hi, [https://i.imgur.com/Qmc4UkV.png](https://i.imgur.com/Qmc4UkV.png)

**Comment by winnipeg21** [comment]
776 gives an Error #005 while 777 is ok. Would be nice to have an FAQ on your wiki section for future reference.

**Comment by zJerino** [comment]
Curiously I am creating it now

**Comment by zJerino** [comment]
But I still don't have the ERROR 005 information created but I can tell you to go to the `/cache/` folder and delete the file called `d158baba76918cba404ac4ed3da2b2ff345227cd.cache`

**Comment by zJerino** [comment]
Then you must reload the page and it should work

**Comment by zJerino** [comment]
- [ ]
