### ISSUE TITLE
Changing the HTML Viewer

### ISSUE THREAD

**Issue by winnipeg21** [zJerino/Mooz-Template#3]
Hey, sorry for the issues, can't seem to find your discord anyone.

Anyway, I tried converting (to the best of my abilities) the template to a dark mode. Tho i'm having the issue of the HTML text editor being black text. Sam said to change a thing in the template.php to use the darkly mode but after many tries i've failed this. 

tldr: make text for the HTML text editor white/set default color.

Thanks

**Comment by zJerino** [comment]
Hello good evening, I would like you to send me the url of your website.

**Comment by winnipeg21** [comment]
https://forums.revivalmc.co

**Comment by zJerino** [comment]
![img](https://i.imgur.com/HafBBEI.png)
Can you disable the CAPTCHA please is it not me to continue?

**Comment by winnipeg21** [comment]
Should be disabled

**Comment by zJerino** [comment]
Well, apparently you have to add the following line

```css
#tinymce > p {
    color: #fff;
}
```

to the file /core/assets/plugins/tinymce/skins/ui/oxide-dark/content.min.css

**Comment by winnipeg21** [comment]
I'll try that when I wake up tmr. Thanks

**Comment by zJerino** [comment]
ok please let me know if you have another problem 😊

**Comment by winnipeg21** [comment]
Sorry to bring this back to light. Your fix worked, but for bullet points, it doesn't work.

EDIT: I fixed it by just clearing CF caching, my fault. Thanks anyways!
